#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Fri Oct 09 07:17:48 GMT 2026
android.nonTransitiveRClass=true
android.usesSdkInManifest.disallowed=false
android.dependency.useConstraints=true
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
isFullBuild=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx5120m -XX\:+UseParallelGC -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.enableJetifier=false
android.useAndroidX=true
ksp.useKSP2=true
android.r8.optimizedResourceShrinking=false
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.r8.strictFullModeForKeepRules=false
systemProp.sun.jnu.encoding=UTF-8
android.nonFinalResIds=false
systemProp.file.encoding=UTF-8
kotlin.jvm.target.validation.mode=IGNORE
org.gradle.unsafe.configuration-cache=true
